# Site configuration
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://songroger.win" # the base hostname & protocol for your site
permalink: /:title/
avatar: /photos/avatar.jpg
about: /photos/about.jpg
favicon: /assets/favicon.ico
# basecss: http://7xof48.com1.z0.glb.clouddn.com/songroger/main.min.css
# Theme specific configuration
title: songroger
description: >
  Hi there, My name is Luozhan.Song, usually I use "songroger" as my ID everywhere.
  I was born and raised in Hunan China. 
  I'm really fond of beautiful design, drawing etc.
keywords: songroger,github

about_bgm: "https://dev.tencent.com/api/share/download/3f03e8c9-2187-454c-ba65-66e7d003a660"

# Contact and social media links
twitter_username: songrogero
github_username: songroger
facebook_username: song.roger.1
instagram_username: songroger198
linkedin_username: songroger

exclude: ['node_modules', 'gulpfile.js', 'package.json']

# defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

kramdown:
  input: GFM

# gems: ['jekyll-paginate']

# Pagination
paginate: 7
paginate_path: /archive/page:num

plugins:
    - jekyll-paginate